name: ansible-lint

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
      - name: Analysing playbook
        run: |
          ansible-lint install/*.yml -x command-instead-of-module,jinja,no-free-form,var-naming,risky-file-permissions,ignore-errors,no-changed-when -v
